const express = require('express');
const router = express.Router();
const { signup, verify, resendCode, magicVerify, login, forgotPassword, resetPassword, completeProfile, getActivityStats, markAttendance, sendCorrespondence, requestCommunityAccess, lockProfile, deleteAccount, checkStatus,getLiturgicalToday } = require('../controllers/student');

router.post('/signup', signup);
router.post('/verify', verify);
router.post('/resend-code', resendCode);
router.get('/magic-verify/:token', magicVerify);
router.post('/login', login);
router.post('/forgot-password', forgotPassword);
router.post('/reset-password/:token', resetPassword);
router.put('/complete-profile/:id', completeProfile);
router.get('/activity-stats/:id', getActivityStats);
router.post('/attendance/:id', markAttendance);
router.post('/correspondence/:id', sendCorrespondence);
router.post('/community-request/:id', requestCommunityAccess);
router.put('/lock-profile/:id', lockProfile);
router.delete('/delete-account/:id', deleteAccount);
router.get('/check-status/:email', checkStatus);
router.get('/liturgical-today', getLiturgicalToday);
module.exports = router;